# Living Documentation Manifest v1.0
# Dynamic, scalable documentation system for AI-assisted development
# This file is the single source of truth for all documentation configuration

version: "1.0"
project: "{{PROJECT_NAME}}"  # Configure in project-config.yaml

# =============================================================================
# DOCUMENT TYPES
# Each type defines a category of documentation with its own schema and behavior
# =============================================================================
document_types:

  # Anti-patterns and bug signatures
  patterns:
    id: patterns
    name: "Bug Patterns"
    description: "Anti-patterns, bug signatures, and lessons learned"
    icon: "ðŸ›"
    tier: B
    path: "BUG_PATTERNS.md"  # Root level (not docs/)
    schema: "schemas/pattern.schema.json"
    template: "templates/pattern.template.md"
    triggers:
      - bug_fix
      - post_mortem
      - regression
    required_fields:
      - id
      - title
      - root_cause
      - fix
      - prevention
    searchable: true
    auto_link: true  # Auto-link pattern IDs in commits/code
    subcategories:  # Group patterns by system
      - multiplayer
      - audio
      - ui
      - thread
      - tooling

  # Best practices and recommended approaches
  golden_paths:
    id: golden_paths
    name: "Golden Paths"
    description: "Best practices and recommended implementation patterns"
    icon: "âœ¨"
    tier: B
    path: "docs/GOLDEN_PATHS.md"
    schema: "schemas/golden-path.schema.json"
    template: "templates/golden-path.template.md"
    triggers:
      - new_feature
      - refactor
      - pattern_discovery
    required_fields:
      - id
      - title
      - context
      - solution
      - examples
    searchable: true

  # Safety rules and invariants
  invariants:
    id: invariants
    name: "Invariants"
    description: "Safety rules that must never be violated"
    icon: "ðŸ›¡ï¸"
    tier: A  # CRITICAL - Must be cited when editing related code
    path: "docs/INVARIANTS.md"
    schema: "schemas/invariant.schema.json"
    template: "templates/invariant.template.md"
    triggers:
      - config_change
      - tier_a_edit
      - safety_critical
    required_fields:
      - id
      - rule
      - rationale
      - violation_example
      - linked_tests
    citation_required: true
    linked_to_tests: true
    subcategories:  # Group invariants by domain
      - thread_safety
      - audio
      - multiplayer
      - security
      - performance

  # Architecture Decision Records
  decisions:
    id: decisions
    name: "Decisions (ADR)"
    description: "Architecture Decision Records"
    icon: "ðŸ“"
    tier: B
    path: "docs/decisions/"
    pattern: "ADR-*.md"  # Multiple files matching pattern
    schema: "schemas/decision.schema.json"
    template: "templates/decision.template.md"
    triggers:
      - arch_change
      - tech_choice
      - breaking_change
    required_fields:
      - id
      - title
      - status
      - context
      - decision
      - consequences
    auto_number: true  # Auto-increment ADR numbers
    subcategories:  # Group by status
      - accepted
      - deprecated
      - proposed

  # Code to documentation mapping
  code_map:
    id: code_map
    name: "Code-Doc Map"
    description: "Maps code files to their documentation"
    icon: "ðŸ—ºï¸"
    tier: C
    path: "docs/CODE_DOC_MAP.md"
    schema: "schemas/code-map.schema.json"
    triggers:
      - new_file
      - file_rename
      - major_refactor
    auto_generate: true  # Can be partially auto-generated

  # Bug tracker (instance-specific, not pattern)
  tracker:
    id: tracker
    name: "Bug Tracker"
    description: "Current bugs and investigation status"
    icon: "ðŸ“‹"
    tier: B
    path: "BUG_TRACKER.md"
    triggers:
      - bug_report
      - bug_fix
      - investigation
    retention: "90d"  # Archive entries older than 90 days
    metrics:
      - name: "bugs_open"
        pattern: 'bugs_open:\s*(\d+)'
      - name: "bugs_fixed"
        pattern: 'bugs_fixed:\s*(\d+)'
      - name: "sev_p0"
        pattern: '"P0":\s*(\d+)'
        weight: 10
      - name: "sev_p1"
        pattern: '"P1":\s*(\d+)'
        weight: 3
      - name: "sev_p2"
        pattern: '"P2":\s*(\d+)'
        weight: 1

  # Changelog
  changelog:
    id: changelog
    name: "Changelog"
    description: "Version history and release notes"
    icon: "ðŸ“"
    tier: A
    path: "CHANGELOG.md"
    triggers:
      - version_bump
      - release
      - any_code_change
    required_on_commit: true

# =============================================================================
# TIERS - Access and citation requirements
# =============================================================================
tiers:
  A:
    name: "Critical"
    description: "Must be cited when editing related code"
    citation_required: true
    pre_commit_block: true
    color: "#ff4444"

  B:
    name: "Important"
    description: "Should be updated when relevant changes occur"
    citation_required: false
    pre_commit_block: false
    color: "#ffaa00"

  C:
    name: "Reference"
    description: "Helpful but not blocking"
    citation_required: false
    pre_commit_block: false
    color: "#44aa44"

  D:
    name: "Legacy/Deprecated"
    description: "No longer actively maintained"
    citation_required: false
    pre_commit_block: false
    color: "#888888"

# =============================================================================
# TRIGGERS - Events that should prompt documentation updates
# =============================================================================
triggers:
  bug_fix:
    description: "When fixing a bug"
    updates: [patterns, tracker, changelog]
    prompt: "Add pattern to BUG_PATTERNS.md?"

  new_feature:
    description: "When adding a new feature"
    updates: [golden_paths, changelog, code_map]
    prompt: "Document the implementation pattern?"

  arch_change:
    description: "When making architectural changes"
    updates: [decisions, invariants]
    prompt: "Create ADR for this decision?"

  config_change:
    description: "When changing configuration"
    updates: [invariants]
    prompt: "Update INVARIANTS.md?"

  tier_a_edit:
    description: "When editing Tier A files"
    updates: [invariants]
    requires_citation: true

  post_mortem:
    description: "After incident resolution"
    updates: [patterns, tracker]

  regression:
    description: "When a bug recurs"
    updates: [patterns]
    escalate: true  # Flag for review

# =============================================================================
# HOOKS - Automated checks and actions
# =============================================================================
hooks:
  session_start:
    - action: git_sync
      command: "git fetch origin {{MAIN_BRANCH}} && git log --oneline -3"
    - action: load_context
      files: [CURRENT_WORK.md, CLAUDE.md]
    - action: version_check
      compare: [local, "origin/{{MAIN_BRANCH}}"]
    - action: staleness_check
      max_age: "7d"

  pre_commit:
    - action: changelog_check
      condition: "code_changed"
      block: true
    - action: tier_a_citation
      condition: "tier_a_files_changed"
      block: true
    - action: pattern_check
      condition: "bug_fix_commit"
      warn: true
    - action: blast_radius
      threshold: 5  # Warn if > 5 files changed

  post_commit:
    - action: update_dashboard
    - action: confidence_score

  post_fix:
    - action: prompt_pattern
      message: "Add this fix to BUG_PATTERNS.md?"

# =============================================================================
# DASHBOARD - Dynamic dashboard configuration
# =============================================================================
dashboard:
  output: "docs/DASHBOARD.md"
  html_output: ".claude/dashboard/index.html"
  history_file: ".claude/dashboard/history.json"
  refresh: "on_change"  # or "manual", "hourly"

  sections:
    - id: health
      title: "Documentation Health"
      type: metrics
      metrics:
        - staleness_score
        - coverage_score
        - citation_compliance

    - id: recent
      title: "Recent Updates"
      type: activity
      max_items: 10

    - id: documents
      title: "Core Documents"
      type: document_list
      show_status: true

    - id: triggers
      title: "Update Triggers"
      type: trigger_matrix

    - id: confidence
      title: "System Confidence"
      type: confidence_scores
      source: "CHANGELOG.md"  # Extract from confidence table

# =============================================================================
# RELATIONSHIPS - How documents relate to each other
# =============================================================================
relationships:
  - from: patterns
    to: golden_paths
    type: "prevents"
    description: "Patterns document what to avoid, golden paths what to do"

  - from: invariants
    to: patterns
    type: "enforces"
    description: "Invariants prevent patterns from recurring"

  - from: decisions
    to: code_map
    type: "implements"
    description: "Decisions are implemented in mapped code"

  - from: tracker
    to: patterns
    type: "graduates_to"
    description: "Fixed bugs graduate to patterns"

# =============================================================================
# AUTO-DISCOVERY - Find documents not explicitly listed
# =============================================================================
discovery:
  enabled: true
  paths:
    - "docs/**/*.md"
    - "*.md"
  exclude:
    - "node_modules/**"
    - ".git/**"
    - "vendor/**"
    - "build/**"
    - "dist/**"
  classify_by:
    - frontmatter  # YAML frontmatter with type field
    - filename_pattern  # ADR-*, PATTERN-*, etc.
    - content_markers  # ## Pattern:, ## Decision:, etc.

# =============================================================================
# LANGUAGE-SPECIFIC CONFIGURATION
# =============================================================================
# Override these in project-config.yaml based on your language
# See core/languages/*.yaml for language-specific defaults
language:
  name: "{{LANGUAGE}}"  # python, javascript, go, rust, java, csharp, etc.
  version_file: "{{VERSION_FILE}}"  # Where version is defined
  version_pattern: "{{VERSION_PATTERN}}"  # Regex to extract version
  code_root: "{{CODE_ROOT}}"  # Root directory for code
  code_extensions: ["{{EXT}}"]  # File extensions to track
  test_pattern: "{{TEST_PATTERN}}"  # Glob for test files
