# Living Documentation Manifest v1.0
# Dynamic, scalable documentation system for AI-assisted development
# This file is the single source of truth for all documentation configuration

version: "1.0"
project: "{{PROJECT_NAME}}"  # Configure in project-config.yaml

# =============================================================================
# DOCUMENT TYPES
# Each type defines a category of documentation with its own schema and behavior
# =============================================================================
document_types:

  # Anti-patterns and bug signatures
  patterns:
    id: patterns
    name: "Bug Patterns"
    description: "Anti-patterns, bug signatures, and lessons learned"
    tier: B
    path: "BUG_PATTERNS.md"
    schema: "schemas/pattern.schema.json"
    template: "templates/pattern.template.md"
    triggers:
      - bug_fix
      - post_mortem
      - regression
    required_fields:
      - id
      - title
      - root_cause
      - fix
      - prevention
    searchable: true
    auto_link: true

  # Best practices and recommended approaches
  golden_paths:
    id: golden_paths
    name: "Golden Paths"
    description: "Best practices and recommended implementation patterns"
    tier: B
    path: "docs/GOLDEN_PATHS.md"
    schema: "schemas/golden-path.schema.json"
    template: "templates/golden-path.template.md"
    triggers:
      - new_feature
      - refactor
      - pattern_discovery
    required_fields:
      - id
      - title
      - context
      - solution
      - examples
    searchable: true

  # Safety rules and invariants
  invariants:
    id: invariants
    name: "Invariants"
    description: "Safety rules that must never be violated"
    tier: A  # CRITICAL - Must be cited when editing related code
    path: "docs/INVARIANTS.md"
    schema: "schemas/invariant.schema.json"
    template: "templates/invariant.template.md"
    triggers:
      - config_change
      - tier_a_edit
      - safety_critical
    required_fields:
      - id
      - rule
      - rationale
      - violation_example
      - linked_tests
    citation_required: true
    linked_to_tests: true

  # Architecture Decision Records
  decisions:
    id: decisions
    name: "Decisions (ADR)"
    description: "Architecture Decision Records"
    tier: B
    path: "docs/decisions/"
    pattern: "ADR-*.md"
    schema: "schemas/decision.schema.json"
    template: "templates/decision.template.md"
    triggers:
      - arch_change
      - tech_choice
      - breaking_change
    required_fields:
      - id
      - title
      - status
      - context
      - decision
      - consequences
    auto_number: true

  # Code to documentation mapping
  code_map:
    id: code_map
    name: "Code-Doc Map"
    description: "Maps code files to their documentation"
    tier: C
    path: "CODE_DOC_MAP.md"
    triggers:
      - new_file
      - file_rename
      - major_refactor
    auto_generate: true

  # Changelog
  changelog:
    id: changelog
    name: "Changelog"
    description: "Version history and release notes"
    tier: A
    path: "CHANGELOG.md"
    triggers:
      - version_bump
      - release
      - any_code_change
    required_on_commit: true

# =============================================================================
# TIERS - Access and citation requirements
# =============================================================================
tiers:
  A:
    name: "Critical"
    description: "Must be cited when editing related code"
    citation_required: true
    pre_commit_block: true

  B:
    name: "Important"
    description: "Should be updated when relevant changes occur"
    citation_required: false
    pre_commit_block: false

  C:
    name: "Reference"
    description: "Helpful but not blocking"
    citation_required: false
    pre_commit_block: false

# =============================================================================
# TRIGGERS - Events that should prompt documentation updates
# =============================================================================
triggers:
  bug_fix:
    description: "When fixing a bug"
    updates: [patterns, changelog]
    prompt: "Add pattern to BUG_PATTERNS.md?"

  new_feature:
    description: "When adding a new feature"
    updates: [golden_paths, changelog, code_map]
    prompt: "Document the implementation pattern?"

  arch_change:
    description: "When making architectural changes"
    updates: [decisions, invariants]
    prompt: "Create ADR for this decision?"

  config_change:
    description: "When changing configuration"
    updates: [invariants]
    prompt: "Update INVARIANTS.md?"

  tier_a_edit:
    description: "When editing Tier A files"
    updates: [invariants]
    requires_citation: true

# =============================================================================
# HOOKS - Automated checks and actions
# =============================================================================
hooks:
  pre_commit:
    - action: changelog_check
      condition: "code_changed"
      block: true
    - action: tier_a_citation
      condition: "tier_a_files_changed"
      block: true
    - action: blast_radius
      threshold: 5

# =============================================================================
# RELATIONSHIPS - How documents relate to each other
# =============================================================================
relationships:
  - from: patterns
    to: golden_paths
    type: "prevents"
    description: "Patterns document what to avoid, golden paths what to do"

  - from: invariants
    to: patterns
    type: "enforces"
    description: "Invariants prevent patterns from recurring"

  - from: decisions
    to: code_map
    type: "implements"
    description: "Decisions are implemented in mapped code"

# =============================================================================
# AUTO-DISCOVERY - Find documents not explicitly listed
# =============================================================================
discovery:
  enabled: true
  paths:
    - "docs/**/*.md"
    - "*.md"
  exclude:
    - "node_modules/**"
    - ".git/**"
    - "vendor/**"
    - "build/**"
    - "dist/**"

# =============================================================================
# LANGUAGE-SPECIFIC CONFIGURATION
# =============================================================================
language:
  name: "{{LANGUAGE}}"
  version_file: "{{VERSION_FILE}}"
  version_pattern: "{{VERSION_PATTERN}}"
  code_root: "{{CODE_ROOT}}"
  code_extensions: ["{{EXT}}"]
  test_pattern: "{{TEST_PATTERN}}"
