#!/bin/bash
# =============================================================================
# Living Documentation Framework - Hook Installer
# =============================================================================
#
# Installs git hooks for Living Documentation validation.
# Run from project root: ./LivingDocFramework/hooks/install.sh
#
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_ROOT="$(pwd)"
GIT_HOOKS_DIR="$PROJECT_ROOT/.git/hooks"

echo "Living Documentation Framework - Hook Installer"
echo "==============================================="
echo ""
echo "Framework: $FRAMEWORK_ROOT"
echo "Project:   $PROJECT_ROOT"
echo "Hooks dir: $GIT_HOOKS_DIR"
echo ""

# Check if .git directory exists
if [ ! -d "$PROJECT_ROOT/.git" ]; then
    echo "❌ Error: Not a git repository"
    echo "   Run this script from your project root directory"
    exit 1
fi

# Check if living-doc-config.yaml exists
if [ ! -f "$PROJECT_ROOT/living-doc-config.yaml" ]; then
    echo "⚠️  Warning: living-doc-config.yaml not found"
    echo "   Creating from template..."
    cp "$FRAMEWORK_ROOT/core/project-config.template.yaml" "$PROJECT_ROOT/living-doc-config.yaml"
    echo "   ✅ Created living-doc-config.yaml - please customize it"
    echo ""
fi

# Create hooks directory if it doesn't exist
mkdir -p "$GIT_HOOKS_DIR"

# Determine framework path relative to project root
REL_PATH=$(realpath --relative-to="$PROJECT_ROOT" "$FRAMEWORK_ROOT")

# Create pre-commit hook
cat > "$GIT_HOOKS_DIR/pre-commit" << EOF
#!/bin/bash
# Living Documentation Framework - Pre-Commit Hook
# Auto-generated by: $REL_PATH/hooks/install.sh

HOOK_SCRIPT="$REL_PATH/hooks/pre-commit"

if [ -f "\$HOOK_SCRIPT" ]; then
    bash "\$HOOK_SCRIPT"
    exit \$?
else
    echo "⚠️  Warning: \$HOOK_SCRIPT not found, skipping doc validation"
    exit 0
fi
EOF

# Create commit-msg hook
cat > "$GIT_HOOKS_DIR/commit-msg" << EOF
#!/bin/bash
# Living Documentation Framework - Commit-Msg Hook
# Auto-generated by: $REL_PATH/hooks/install.sh

HOOK_SCRIPT="$REL_PATH/hooks/commit-msg"

if [ -f "\$HOOK_SCRIPT" ]; then
    bash "\$HOOK_SCRIPT" "\$1"
    exit \$?
else
    echo "⚠️  Warning: \$HOOK_SCRIPT not found, skipping commit message validation"
    exit 0
fi
EOF

# Create post-commit hook
cat > "$GIT_HOOKS_DIR/post-commit" << EOF
#!/bin/bash
# Living Documentation Framework - Post-Commit Hook
# Auto-generated by: $REL_PATH/hooks/install.sh

HOOK_SCRIPT="$REL_PATH/hooks/post-commit"

if [ -f "\$HOOK_SCRIPT" ]; then
    bash "\$HOOK_SCRIPT"
    # Don't fail the commit if post-commit hook fails
    exit 0
else
    exit 0
fi
EOF

# Make hooks executable
chmod +x "$GIT_HOOKS_DIR/pre-commit"
chmod +x "$GIT_HOOKS_DIR/commit-msg"
chmod +x "$GIT_HOOKS_DIR/post-commit"

# Make framework hooks executable
chmod +x "$FRAMEWORK_ROOT/hooks/pre-commit" 2>/dev/null || true
chmod +x "$FRAMEWORK_ROOT/hooks/commit-msg" 2>/dev/null || true
chmod +x "$FRAMEWORK_ROOT/hooks/post-commit" 2>/dev/null || true

echo "✅ Installed hooks:"
echo "   • pre-commit     - Documentation validation"
echo "   • commit-msg     - Commit message format"
echo "   • post-commit    - Dashboard updates"
echo ""
echo "📋 Hook locations:"
echo "   .git/hooks/pre-commit → $REL_PATH/hooks/pre-commit"
echo "   .git/hooks/commit-msg → $REL_PATH/hooks/commit-msg"
echo "   .git/hooks/post-commit → $REL_PATH/hooks/post-commit"
echo ""
echo "💡 Usage tips:"
echo "   • Test hooks:  git commit --dry-run"
echo "   • Skip hooks:  git commit --no-verify"
echo "   • Configure:   Edit living-doc-config.yaml"
echo ""
echo "✨ Done! Hooks are now active."
